services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.server  
    container_name: server
    ports:
      - "8000:8000"  
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin123
      - MYSQL_DB=todo_directory
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.client  
    container_name: client
    ports:
      - "80:80"  
    depends_on:
      - backend

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: todo_directory
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
